### ISSUE TITLE
Release 2.1.3

### ISSUE THREAD

**Issue by ramiro** [pymssql/pymssql#436]
From the [stable-2.1.x branch](https://github.com/pymssql/pymssql/tree/stable-2.1.x).

Tentative list of changes to be included:

- [x] Undo *Link FreeTDS dynamically + require OpenSSL* change I introduced for 2.1.2 on the official Windows binaries (#399, #400, #422). This includes updating our docs.
- [x] Update bundled Linux static FreeTDS to v0.95.95 to be on par with Windows. This includes updating our docs.
- [x] ~~Other fixes (no features)~~ only (a trivial) one:  https://github.com/pymssql/pymssql/commit/f5377439145b5a2358a874651bfa036999214da0
- [x] Publish that our Window CI is now at https://ci.appveyor.com/project/level12/pymssql
- [x] Publish *manylinux* wheels for Linux as part of our official binaries? (#282)
- [ ] ~~Allow pymssql to be compiled against FreeTDS 1.0 (#432) (or should simply keep announcing compatibility with FreeTDS <= 0.95 and defer compatibility with 1.0 for a future release)?~~
- [x] Publish a RC at Test PYPI (https://testpypi.python.org/pypi/pymssql) and ask the community for testing.
- [x] Update docs
- [x] Change version ID in `pymssql_version.h`
- [x] Update encrypted PyPI credentials in `appveyor.yml`
- [x] Update ChangeLog (actual release date, Note about lack of s/OpenSSL/SSL/
- [x] Make sure ReadTheDocs picks the `stable-2.1.x` branch
- [x] Consider uploading final PyPI files via Warehouse instead of PyPI itself to avoid broken uploads. See https://mail.python.org/pipermail/distutils-sig/2016-June/029083.html

Changes to this list are welcome!

**Comment by rhavenn** [comment]
Getting a build issue on FreeBSD. It's the same error as #432 when using pymssql-2.1.1.

It looks like the bug was fixed to work with FreeTDS 1.0 better in 2.1.3, but when trying to compile 2.1.3-dev2 (commit# 096b463 ) I'm getting a cython build error. It looks like you've got a declaration issue.

`_mssql.pxd: cdef int convert_python_value(self, object value, BYTE **, int*, int*) except -1`
and
`_mssql.pyx: cdef int convert_python_value(self, object value, BYTE **dbValue, int *dbtype, int *length) except -1`

**Comment by ramiro** [comment]
> Getting a build issue on FreeBSD. It's the same error as #432 when using pymssql-2.1.1.

Yes, 2.1.1 was released five months before before FreeTDS 1.0.  
> 
> It looks like the bug was fixed to work with FreeTDS 1.0 better in 2.1.3

No, per the above check list we don't plan to fix compatibility with FreeTDS 1.0  in 2.1.x. Hopefully for 2.2 which is in preparation on ther master branch. Any help is welcome.
>but when trying to compile 2.1.3-dev2 (commit# 096b463 ) I'm getting a cython build error. It looks like you've got a declaration issue.
> 
> _mssql.pxd: cdef int convert_python_value(self, object value, BYTE **, int*, int*) except -1
> and
> _mssql.pyx: cdef int convert_python_value(self, object value, BYTE **dbValue, int *dbtype, int *length) except -1
> 
> The actual error I'm getting is:
> _mssql.pyx:831:9: Signature not compatible with previous declaration


I see no signature mismatch there. Are you sure you are using the version of the pymssql code you think you are using?

Is it possible you are aren't using 2.1.3 but 2.1.1 as we fixed a real error there for for 2.1.2: 6206686235ae711047e933e559adb2b3235d4c97

**Comment by ramiro** [comment]
Done.
