### ISSUE TITLE
The Pymssql Project is Being Discontinued

### ISSUE THREAD

**Issue by rsyring** [pymssql/pymssql#668]
Thank you to everyone who has contributed to pymssql over the years.  Unfortunately, I believe it's time to discontinue pymssql.  It provides an incredible amount of utility to those of us that need to connect to MSSQL from Python.  But, as a project, it has failed to attract enough interest/talent/funding to maintain it.

Why discontinue it and not let someone else maintain it?  We've tried over the years.  See #516.  We have got a few people drop by to help occasionally, but nothing sustained enough to feel like transfer of the project was warranted.

I had always hoped my consulting business would be able to help maintain the library for clients that use it.  But there is too much work here for us to tackle that doesn't really benefit our client's usage and we transitioned to PyODBC earlier this year.

I'm also concerned that if I simply abandon the project a bad actor could gain control and start installing nasty stuff on what I am sure is a lot of corporate servers.

It's my hope that by discontinuing this project better solutions will be developed and/or adopted to take it's place.

# Other Related Issues

* Proposal to discontinue pymssql in favor of pyodbc #477
* Maintainers Needed - Apply Within #516
* Finding grants/funding for pymssql development #621

# Alternatives

* [pyodbc](https://github.com/mkleehammer/pyodbc): Microsoft backed
  * But see: https://github.com/level12/sqlalchemy_pyodbc_mssql
* [ctds](https://github.com/zillow/ctds): by Zillow
* [Turboodbc](https://turbodbc.readthedocs.io/): has performance enhancements including NumPy and Apache Arrow support
* [adodbapi](https://sourceforge.net/projects/adodbapi/): Windows only

# Interested in Taking Over?

Just fork pymssql and start your own project.  Gain momentum, show progress, and I'd be happy to link to your project from here.

# Next Steps

I'm going to leave this issue open for suggestions on how best to deprecate/discontinue pymssql as a project.  I'm sure there will be some who will suddenly be very interested in helping.  I won't be considering those requests at this point.  If you want to help, see above about forking.

At the end of November, 2019 I'm going to Archive this GH repository which will make it read-only.

I'll also need to figure out how to deprecate packages on PyPI so that people installing know the project is being discontinued.  

# ToDos

* [x] Notify relevant mailing lists
* [x] Update readme with notice
* [x] Publish readme notice to PyPI
* [x] Put notification into project setup/install process somehow?
* [ ] Close all open issues and PRs with notice (is there an automation tool that can help with this somewhere?)
* [ ] Archive GitHub Project
* [x] Setup RTD to no longer use pymssql.org, discontinue renewal of that domain

**Comment by guruofgentoo** [comment]
FWIW, [sqlalchemy_pyodbc_mssql](https://pypi.org/project/sqlalchemy-pyodbc-mssql/) is up on PyPI and has been used in one of our largest apps for several months without concerns.

The intent there was to wrap up the pain points of using pyodbc with MSSQL. Operationally, pairing pyodbc with the custom dialect ended up being close to a drop-in replacement for pymssql.

**Comment by wesm** [comment]
FWIW, turbodbc offers a much faster alternative to pyodbc now in 2019, so can also recommend it for cases where bulk export performance matters a lot

https://turbodbc.readthedocs.io

**Comment by vernondcole** [comment]
And, for an open-source, pure Python alternative, [adodbapi](https://sourceforge.net/projects/adodbapi/),
which, if I can get the correct patch in soon enough, will also be correct in the next release of pywin32.

**Comment by bemoody** [comment]
I'm sorry to hear this.

I have one request:

> Close all open issues and PRs with notice

Please don't do that.  If anyone decides in the future that they want to try to resurrect the project, having a list of known bugs is useful information.  Or, depending on how you look at it, having a list of known bugs might encourage prospective ressurectors to work on one of those alternative projects instead. ;)

**Comment by RadixSeven** [comment]
The error message on the new version should say `pymssql<3.0` not `<=3.0` (3.0 is the one that errors to show the discontinuation.

**Comment by rsyring** [comment]
@RadixSeven thanks for reporting.  Sorry for the confusion.  That is fixed now.

**Comment by decaz** [comment]
@rsyring what do you think about merge of #659? This minor change of code will give opportunity to use the library with the latest Python version. I see there are side packages appear (https://pypi.org/project/pymssql-py38/ for example) and there is no control under source code of them.

**Comment by rsyring** [comment]
@decaz on it's face it seems like a reasonable request.  The problem though isn't the merge.  It's the release.  I no longer have a system that builds all the various wheels to make a pymssql release across supported versions.

**Comment by mnewman-iress** [comment]
For those using Alpine, pyodbc does not appear to be a drop in replacement as MS does not provide an ODBC driver for Alpine:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver15

Upvote the issue here to help get the Alpine support prioritized:
https://github.com/microsoft/msphpsql/issues/300

**Comment by jason-brian-anderson** [comment]
I use this module in automated docker builds.and would prefer not to go rebuild code with another module at this time.  is there a way to ignore the deprecation errors with pip?

**Comment by rsyring** [comment]
@jason-brian-anderson: the error message upon install as well as the readme here and on pypi all say:

> To install the last working released version, install with a version specifier like "pymssql<3.0". E.g. pip install "pymssql<3.0"

**Comment by devrsw** [comment]
Just as an update here - Microsoft will be building in Alpine support for pyodbc in the next OSBC release: https://github.com/microsoft/msphpsql/issues/300#issuecomment-557297195.

**Comment by musbur** [comment]
This is a shame! Can pyodbc be used to connect from a Linux client? I thought ODBC was Windows only.

**Comment by gordthompson** [comment]
> Can pyodbc be used to connect from a Linux client?

Yes, it can.

**Comment by yehoshuadimarsky** [comment]
> FWIW, turbodbc offers a much faster alternative to pyodbc now in 2019, so can also recommend it for cases where bulk export performance matters a lot
> 
> https://turbodbc.readthedocs.io

Additionally, for MS SQL specific, I think the fastest performance (by orders of magnitude) comes from using the BCP utility. I wrote a wrapper around it to integrate seamlessly with Pandas, see here (shameless plug, yes, but I think can be super helpful):

https://github.com/yehoshuadimarsky/bcpandas

**Comment by codeman101** [comment]
It's a shame this driver was discontinued because it's much more sqlalchemy friendly than pyodbc. Yes there's the pip package sqlalchemy_pyodbc but you still have to separately add a driver and then add that to the connection unless you use dsn.

**Comment by wesm** [comment]
At the risk of stating the obvious, there is no fundamental reason the project _needs_ to be discontinued, but it does need to be adopted by a new maintainers. Perhaps there are people at Microsoft which might be interested in helping with this project

**Comment by gordthompson** [comment]
@wesm  - Microsoft already officially supports pyodbc, and a couple of Microsoft employees contribute to that project with bugfixes and features related to accessing SQL Server, Azure SQL, etc..

**Comment by wesm** [comment]
@gordthompson have you run the performance numbers comparing pymssql / TDS data export versus pyodbc? I don't know what the current status is but in my personal experience using these projects on SQL Server, pymssql yielded better performance. If the position of Microsoft is that using FreeTDS to access SQL Server is deprecated, then I understand

**Comment by gordthompson** [comment]
@wesm - One of the Microsoft contributors implemented [fast_executemany](https://github.com/mkleehammer/pyodbc/wiki/Features-beyond-the-DB-API#fast_executemany) which can speed up `executemany` operations significantly.

>  have you run the performance numbers

I haven't done a performance comparison between pyodbc and pymssql, but I did do one between [pyodbc and turbodbc](https://stackoverflow.com/a/53998717/2144390).

>  If the position of Microsoft is that using FreeTDS to access SQL Server is deprecated

AFAIK Microsoft never officially supported FreeTDS, so it can't really be deprecated.

**Comment by wesm** [comment]
> AFAIK Microsoft never officially supported FreeTDS, so it can't really be deprecated.

Sorry, I meant using TDS / "native" protocol in general versus ODBC

**Comment by termim** [comment]
IMHO this uninstallable "discontinuation" release on PyPi is just unwise and even impolite. 
Potentially it broke automation scripts for 1.6k projects that use Pymssql just to tell their
developers that current Pymssql maintainer believes that Pymssql should be discontinued.
And now if someone would step up for maintaining Pymssql all these 1.6k projects should be 
again notified to change their requirements?

**Comment by wesm** [comment]
I would agree with @termim -- I can't say I've ever heard of maintainers crippling the default PyPI release of a project because they don't plan to make more releases. What do you think about deleting this release, or making a patch release with the updated README?

**Comment by antgel** [comment]
Agreed. Why blow it up? Why not just let this hang around and see what happens i.e. if the community picks it up, instead of forcing some number of forks and diluting whatever effort remains?

**Comment by rsyring** [comment]
> IMHO this uninstallable "discontinuation" release on PyPi is just unwise and even impolite.
> Agreed. Why blow it up? Why not just let this hang around and see what happens i.e. if the community picks it up, instead of forcing some number of forks and diluting whatever effort remains?

Just in case you missed it, I did leave my explanation for why I did it this way in the issue body above.  I understand not everyone would agree with that approach, but felt it was necessary in order to communicate the state of the project to those that use it.  Breaking builds was actually the point, in order to notify people who would not otherwise notice that the project was aging and now discontinued and that they may want to consider finding an alternative.

The workaround to get a build/install working again is simple, should take no more than minutes to apply, and was done with a major version bump according to semver.  In some ways, you could consider pymssql 3.0 a new release with considerable backwards compatibility issues.  :o/

> What do you think about deleting this release, or making a patch release with the updated README?

Sorry, I don't plan to make any future releases.

**Comment by wesm** [comment]
@rsyring would you be willing to make me an admin here and on PyPI and I can take responsibility for this? I am “wesm” on PyPI

**Comment by houc** [comment]
呃呃，我就是说，怎么python3.8不管怎么调都要报错，原来如此哦。好遗憾pymssql团队舍弃这个项目哦。

**Comment by wesm** [comment]
@rsyring following up about my request. I am a benevolent actor and only trying to help. Thank you

**Comment by rsyring** [comment]
@wesm please email me and let's discuss a bit: randy.syring@level12.io.  Thanks.

**Comment by chenbr** [comment]
> I use this module in automated docker builds.and would prefer not to go rebuild code with another module at this time. is there a way to ignore the deprecation errors with pip? my requirements.txt is set to pymssql==2.1.4

im getting the same thing now. Is there a way to ignore this???

**Comment by DoctorLai** [comment]
On Python 3.7.5 you will see the following warnings:
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working`
The latest working version is 'pymssql<3.0', is there an easy way to fix this?
 is there a way modify locally the installed package?

**Comment by elijahgagne** [comment]
Yeah, I'm not seeing 2.1.4 as an option
```
[egagne:~/lenel_sql_server_clone] [.venv] master* 6s 1 ± pip install -r requirements.txt
Collecting pymssql<3.0
  Downloading https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz (691kB)
     |████████████████████████████████| 696kB 385kB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/egagne/code/dartgit/dba/python/lenel_sql_server_clone/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z6/8mvd7dm129s1m50ncpx1t6700000gn/T/pip-install-xq1fn2ec/pymssql/setup.py'"'"'; __file__='"'"'/private/var/folders/z6/8mvd7dm129s1m50ncpx1t6700000gn/T/pip-install-xq1fn2ec/pymssql/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/z6/8mvd7dm129s1m50ncpx1t6700000gn/T/pip-install-xq1fn2ec/pymssql/pip-egg-info
         cwd: /private/var/folders/z6/8mvd7dm129s1m50ncpx1t6700000gn/T/pip-install-xq1fn2ec/pymssql/
    Complete output (7 lines):
    /Users/egagne/code/dartgit/dba/python/lenel_sql_server_clone/.venv/lib/python3.7/site-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
```

**Comment by rsyring** [comment]
@wesm has offered to take over responsibility for the project.  My understanding is that he doesn't have time to maintain the project and will simply be resurrecting it to put it on life support, potentially making some 3.8 releases.  I'm not convinced that's the best approach, but my main goal has been to get out from being responsible for the maintenance of this project and to not see it fall into the hands of a bad actor.  Letting @wesm assume responsibility accomplishes that goal.

I do think it makes sense to release those as 2.1.x and leave the breaking 3.x release intact, so that the project isn't "ghosted" by it's maintainers.  But, I don't think @wesm intends to do that and that's ok because very shortly he'll be the one calling the shots.  :)

I wish you all the best with this project in 2020 and beyond.

**Comment by wesm** [comment]
Thanks. I just removed the 3.0.x releases from PyPI so `pip install pymssql` (version unqualified) works again. I will look at options to publish an "unmaintained package" warning on PyPI -- I don't know what the prior RM's workflow for publishing the wheels was so as soon as I know that I may be able to just do a 2.1.5 release and make sure it also works on Python 3.8. I may also add a less obtrusive deprecation message on import (that can be disabled with an environment variable) to advise users to move to a new package

Thanks @rsyring for your and your colleagues' work maintaining the package.

**Comment by mullenkamp** [comment]
Thanks @rsyring for all your hard work on the project! It was very appreciated!

**Comment by Chris2048** [comment]
Hi @wesm , will this project still be accepting PRs?

**Comment by wesm** [comment]
It will accept PRs. I'll need some volunteers to help with automating the building and collecting of wheel packages for PyPI, otherwise it will be difficult to make releases

**Comment by stjudeaa** [comment]
Myself and another developer are willing to help on this project as we have come to appreciate it at our organization over the last 4 years. @rsyring how you are leaving this project is most unappreciated.

**Comment by wesm** [comment]
@stjudeaa we've worked things out so that `pip install pymssql` still works. Maintainers are free to leave a project at any time.

This project is currently in need of maintainers to help with testing and merging PRs and to help with packaging to make new release. If you'd like to help with this please get in touch with me offline

**Comment by linceaerian** [comment]
@wesm 

I dunno how to do it on Github, I'm a Gitlab user.
In case it help, the scripting I use to do a quick & dirty publish in my Gitlab CI/CD is:

```bash
.deploy_pipy: &deploy_pipy
  image: python:latest
  before_script:
    - rm -rf dist
    - pip3 install wheel twine
  script:
    - echo "Publishing to ${PYPI_REPO}"
    - sed -i "s/CURRENT_VERSION/$CI_COMMIT_REF_NAME/g" ${CI_PROJECT_DIR}/setup.py
    - echo "[distutils]" >> ~/.pypirc
    - echo "index-servers =" >> ~/.pypirc
    - echo "    nexus" >> ~/.pypirc
    - echo "" >> ~/.pypirc
    - echo "[nexus]" >> ~/.pypirc
    - echo "${PYPI_REPO}" >> ~/.pypirc
    - echo "${PYPI_USER}" >> ~/.pypirc
    - echo "${PYPI_PASSWORD}" >> ~/.pypirc
    - python3 setup.py check sdist bdist
    - python3 setup.py sdist bdist_wheel
    - twine upload -r nexus dist/*.tar.gz
  artifacts:
    paths:
      - "dist/*.tar.gz"
      - "dist/*.whl"
    expire_in: 1 week
```
And I also automate the release (Patchnotes+auto-version increment) using a semantic-release CI/CD.
https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#ci-configuration

**Comment by noisycomputation** [comment]
If it is helpful either to the current maintainer of this repo or to folks trying to get pymssql working, my fork at https://github.com/noisycomputation/pymssql-linux builds successfully (can be verified by following CircleCI status badge on top of the README).

The resulting source distribution and wheels for several versions of Python have been pushed to https://pypi.org/project/pymssql-linux, and can thus be installed with pip.

Notably, the CircleCI test config from the upstream (i.e. this) repo is broken. Rather dangerously so, since failed tests show up as passed in CircleCI. As a result, they are not currently even being run, because it is safer to transparently run no tests than to give the false appearance of passing tests. I have tested the Python 3.7 and 3.8 wheels in usage, and that satisfies me for my relatively narrow use case.

I know that this is not the best way to contribute, but unfortunately I do not currently have the bandwidth to do much more than this. The code at my fork compiles, and the CircleCI workflow is valid for Linux, which may at least give someone a starting point to fix up the build process in this repo and to bring it under test.

That being said, @wesm, if you'd like to stage direct me and give me some narrow tasks, I can bring over some of my changes as a PR.

**Comment by wesm** [comment]
I'm afraid I can't offer much at this point other than to oversee the adoption of this project by new maintainers. A lot of people use this project (~1M installs per month according to https://pypistats.org/packages/pymssql) but no one has stepped forward to commit to maintaining it. Such is the tragedy of the commons. I am only here because I felt that crippling the project on PyPI was inappropriate.

**Comment by luislezcair** [comment]
Can you add [python-tds](https://github.com/denisenkom/pytds) to the list of alternatives? I found is pretty much a drop-in replacement for pymssql

**Comment by fentonscode** [comment]
@wesm @noisycomputation @rsyring  I am currently working on a large academic project which is in need of porting into professional production (or at least taking working practices from it). It is highly likely we will be using MS SQL Server and our users would give us push-back on having to install ODBC drivers - if you are positive there will be interest then I will add a note to possibly take on a fork/adoption as an option (or at least be a contributor in the short term). It is likely our use case will involve large HPC clusters on at least 7 different operating systems, so I might be able to provide a good test case if you all develop something instead. We currently use `sqlite3` on local hosts and `psycopg2` to demonstrate remote SQL - but the server we have available is an existing SQL Server 2016 node, hence my interest in `pymssql`!

I'm fairly new to the GitHub community (as previous commercial work was closed-source), but it appears there's something to salvage here.

**Comment by termim** [comment]
@wesm Hi, could you please add me as a maintainer. I'm an old time user of pymssql and now I've got some spare time to give back to the project. I'm planning to fix CI and update it for the last python release.

**Comment by wesm** [comment]
Done.

**Comment by fredderf81** [comment]
good day all - i am trying to use Orange3 via anaconda to connect to MSSQL server. apparently ONLY pymssql works with it? is anyone currently using Orange3 / python 3.8 in windows 10 to connect?? what have you installed to get this to work. i have google'd the entire web for 3 days and have found zero help.

**Comment by termim** [comment]
@fredderf81 Google is you friend: [https://www.google.com/search?q=conda+orange3+install](url).
If you have any specific problem installing pymssql please open a new issue, this one is closed.

**Comment by fredderf81** [comment]
> @fredderf81 Google is you friend: [https://www.google.com/search?q=conda+orange3+install](url).
> If you have any specific problem installing pymssql please open a new issue, this one is closed.

no worries - i have google'd around as stated for 3 days and found no help anywhere over many many webpages. everything is ancient and there is no real structure around support. i solved the issue by installing ubuntu via a oracle virtual box and then installing pymssql.

which didn't do anything anyway because orange3 won't import large datasets so it was all a waste of time.

**Comment by Warfront1** [comment]
@termim Has the decision to discontinue Pymssql been reversed? I haven't seen it stated anywhere directly, but it would look like there are maintainers available to keep this project going. Or the suggestion still valid to fork this project if you want to continue development?

**Comment by termim** [comment]
Yes, it has reversed. You are very welcome to send bug reports and pull requests here as well as discuss it in Discussions.
